extends Object
class_name Utils

enum MessageType {
	RESPONSE_OK = 0x01,
	ERROR_UNEXISTING_MESSAGE_TYPE = 0x02,
	ERROR_TO_FEW_BYTES = 0x03,
	JUST_STRING = 0x0a,
	SIGN_UP = 0x10,
	ERROR_LOGIN_ALREADY_EXISTS = 0x1f,
	ERROR_INVALID_LOGIN = 0x1e,
	ERROR_INVALID_HASHED_PASSWORD = 0x1d,
	ERROR_INVALID_SALT = 0x1c,
	ASK_FOR_SALT = 0x11,
	SALT = 0x12,
	HASHED_PASSWORD = 0x13,
	TEST_BYTE_BY_BYTE = 0xff
}

static func salt_len() -> int:
	return 11
